/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as ResumeBuilderIndexRouteImport } from './routes/resume-builder/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email/$token'
import { Route as ResumesUploadRouteImport } from './routes/resumes.upload'
import { Route as ResumeBuilderNewRouteImport } from './routes/resume-builder/new'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AnalysisIdRouteImport } from './routes/analysis/$id'
import { Route as ResumeBuilderIdEditRouteImport } from './routes/resume-builder/$id.edit'

const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderIndexRoute = ResumeBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeBuilderRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesUploadRoute = ResumesUploadRouteImport.update({
  id: '/resumes/upload',
  path: '/resumes/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderNewRoute = ResumeBuilderNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ResumeBuilderRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalysisRoute,
} as any)
const ResumeBuilderIdEditRoute = ResumeBuilderIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ResumeBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resume-builder': typeof ResumeBuilderRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/jobs/new': typeof JobsNewRoute
  '/resume-builder/new': typeof ResumeBuilderNewRoute
  '/resumes/upload': typeof ResumesUploadRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/resume-builder/': typeof ResumeBuilderIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/resume-builder/$id/edit': typeof ResumeBuilderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/jobs/new': typeof JobsNewRoute
  '/resume-builder/new': typeof ResumeBuilderNewRoute
  '/resumes/upload': typeof ResumesUploadRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/analysis': typeof AnalysisIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/resume-builder': typeof ResumeBuilderIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/resume-builder/$id/edit': typeof ResumeBuilderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resume-builder': typeof ResumeBuilderRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/jobs/new': typeof JobsNewRoute
  '/resume-builder/new': typeof ResumeBuilderNewRoute
  '/resumes/upload': typeof ResumesUploadRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/resume-builder/': typeof ResumeBuilderIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/resume-builder/$id/edit': typeof ResumeBuilderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/resume-builder'
    | '/analysis/$id'
    | '/auth/callback'
    | '/auth/error'
    | '/jobs/new'
    | '/resume-builder/new'
    | '/resumes/upload'
    | '/verify-email/$token'
    | '/analysis/'
    | '/jobs/'
    | '/resume-builder/'
    | '/resumes/'
    | '/verify-email/'
    | '/resume-builder/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/analysis/$id'
    | '/auth/callback'
    | '/auth/error'
    | '/jobs/new'
    | '/resume-builder/new'
    | '/resumes/upload'
    | '/verify-email/$token'
    | '/analysis'
    | '/jobs'
    | '/resume-builder'
    | '/resumes'
    | '/verify-email'
    | '/resume-builder/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/resume-builder'
    | '/analysis/$id'
    | '/auth/callback'
    | '/auth/error'
    | '/jobs/new'
    | '/resume-builder/new'
    | '/resumes/upload'
    | '/verify-email/$token'
    | '/analysis/'
    | '/jobs/'
    | '/resume-builder/'
    | '/resumes/'
    | '/verify-email/'
    | '/resume-builder/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResumeBuilderRoute: typeof ResumeBuilderRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  JobsNewRoute: typeof JobsNewRoute
  ResumesUploadRoute: typeof ResumesUploadRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder/': {
      id: '/resume-builder/'
      path: '/'
      fullPath: '/resume-builder/'
      preLoaderRoute: typeof ResumeBuilderIndexRouteImport
      parentRoute: typeof ResumeBuilderRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/upload': {
      id: '/resumes/upload'
      path: '/resumes/upload'
      fullPath: '/resumes/upload'
      preLoaderRoute: typeof ResumesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder/new': {
      id: '/resume-builder/new'
      path: '/new'
      fullPath: '/resume-builder/new'
      preLoaderRoute: typeof ResumeBuilderNewRouteImport
      parentRoute: typeof ResumeBuilderRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/resume-builder/$id/edit': {
      id: '/resume-builder/$id/edit'
      path: '/$id/edit'
      fullPath: '/resume-builder/$id/edit'
      preLoaderRoute: typeof ResumeBuilderIdEditRouteImport
      parentRoute: typeof ResumeBuilderRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisIdRoute: typeof AnalysisIdRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisIdRoute: AnalysisIdRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface ResumeBuilderRouteChildren {
  ResumeBuilderNewRoute: typeof ResumeBuilderNewRoute
  ResumeBuilderIndexRoute: typeof ResumeBuilderIndexRoute
  ResumeBuilderIdEditRoute: typeof ResumeBuilderIdEditRoute
}

const ResumeBuilderRouteChildren: ResumeBuilderRouteChildren = {
  ResumeBuilderNewRoute: ResumeBuilderNewRoute,
  ResumeBuilderIndexRoute: ResumeBuilderIndexRoute,
  ResumeBuilderIdEditRoute: ResumeBuilderIdEditRoute,
}

const ResumeBuilderRouteWithChildren = ResumeBuilderRoute._addFileChildren(
  ResumeBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResumeBuilderRoute: ResumeBuilderRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  JobsNewRoute: JobsNewRoute,
  ResumesUploadRoute: ResumesUploadRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
